from tabulate import tabulate

_SEVERITY_WEIGHT = {"LOW":1, "MEDIUM":2, "HIGH":3, "CRITICAL":4}
_RADON_WEIGHT = {"A":0, "B":1, "C":2, "D":3, "E":4, "F":5}

def score(item:dict)->float:
    if item["tool"]=="bandit":
        return 10 + _SEVERITY_WEIGHT.get(item.get("severity","LOW"),1)*5
    if item["tool"]=="flake8":
        return 5
    if item["tool"]=="radon":
        return 2 + _RADON_WEIGHT.get(item.get("rank","A"),0)*2
    return 1

def aggregate_findings(files, flake8, bandit, radon, max_issues=50):
    all_items = flake8 + bandit + radon
    for x in all_items:
        x["score"] = score(x)
    all_items.sort(key=lambda x: x["score"], reverse=True)
    return all_items[:max_issues]

def render_markdown(findings:list[dict], diff_range:str, llm:bool=False)->str:
    header = f"# Code Review Report\n\nGit range: `{diff_range}`\n\n"
    table = []
    for f in findings:
        row = [f.get("tool"), f.get("file"), f.get("line"),
               f.get("code", f.get("rank","")), f.get("msg", f.get("name","")) , f"{f['score']:.1f}"]
        table.append(row)
    md = header + "## Ranked Issues\n\n" + tabulate(
        table, headers=["Tool","File","Line","Code/Rank","Message/Block","Score"],
        tablefmt="github"
    ) + "\n\n"
    if llm:
        md += "_LLM hints disabled for OSS demo._\n"
    md += "\n> Generated by ai-code-review-lite\n"
    return md
